### ISSUE TITLE
Feature: Simplified view for "non-technical" users on shared regex 

### ISSUE THREAD

**Issue by gcosta87** [firasdib/regex101-translations#18]
Hi!

I would like to request a feature: a simplified view on shared links, for those users who only want to test a regex, without seeing all the technical details.

I use regex101 in my work to analyze fixed-length plain text files pertaining to (data exchange) specifications. My co-workers are not technical users, but sometimes they need to validate (test) those records.

I think it would be opportune to hide the technical details: explanation and definition of regex (for example). I think that this way, the gui would be more friendly or comfortable for this type of users.

I thank you in advance ;)

**Comment by working-name** [comment]
Hi @gcosta87, thanks for getting involved in making regex101.com even better! You might wish to [re-post this here](https://github.com/firasdib/Regex101/issues/new) instead, where it gets better visibility as far as site development is concerned. This particular repo handles translation-specific issues.

Have a great one!

**Comment by gcosta87** [comment]
Hi
I thank you for showing me my error. I have recently republished where appropriate. I apologize for my mistake. Please close this one

**Comment by working-name** [comment]
It's not a problem at all. Thanks again! 👍
