### ISSUE TITLE
Translations still in active development?

### ISSUE THREAD

**Issue by krollster** [firasdib/regex101-translations#20]
Hi @firasdib 

are the translation files still in active development?
If so I'd like to help with the German translation file. Is that file up to date with all the english phrases that need to be translated?

**Comment by working-name** [comment]
Hi @krollster, while we wait for firasdib to confirm, I just wanted to let you know that there's already an effort underway: https://r101.cf/projects/regex101/www/de/ (should you prefer a UI)

Thanks!

**Comment by firasdib** [comment]
Yes, you can select french and dutch now on the site. They are, however, quite incomplete.

**Comment by firasdib** [comment]
@krollster Thank you. I'd really appreciate if you could help fill out the translations.

**Comment by krollster** [comment]
Sure. I started on the JSON file in this repo last night, but then after a while it dawned on me to better check if it was still active or other people had already continued on it elsewhere. Glad I did.

**Comment by firasdib** [comment]
The website (r101.cf) should automatically sync over to this repo.
