### ISSUE TITLE
Tricky order of strings

### ISSUE THREAD

**Issue by Cosmatevs** [firasdib/regex101-translations#21]
Instead of alphabetical order, the strings should be grouped by place where they are on the page. It would give some context and would help to make translations more accurate.

**Comment by Doqnach** [comment]
many strings can be used in more than one spot, how would you handle that?

**Comment by Cosmatevs** [comment]
Some occurrences of duplicates could be skipped if they always appear together or in the same context. The other ones could be commented – I mean: excluded from executing – with a note that they have appeared before.

**Comment by firasdib** [comment]
@Cosmatevs All duplicates must be skipped, or people will translate the same string twice.

You can not have comments inside JSON files.

**Comment by Cosmatevs** [comment]
So just skip all duplicates and it would still be a better solution than the alphabetical order.

**Comment by firasdib** [comment]
Yes, I will do so.

@working-name Will a change to the english.json cause issues?

**Comment by working-name** [comment]
My bad just noticed this. I'm not sure but if it has a seizure I'll just reorder/reimport everything to match the new `english`, so go for it, whatever helps with transitions I'm down.
