### ISSUE TITLE
Italian localization

### ISSUE THREAD

**Issue by duckyb** [firasdib/regex101-translations#23]
Hi, I have used regex101 many times and I would love to give something back by providing the localization for italian. Can I make a PR in this repository?

---

I noticed that there is already a file for italian but the Italian option is not present on the website, why is that so?

**Comment by working-name** [comment]
Hi @duckyb that would be awesome if you tackled the italian translation. I'm currently attempting to bring back the weblate site (web front-end to translations), had an unfortunate raid failure. 

If you prefer a PR, that's also okay. Just keep in mind that the English source cannot be changed.

Thank you!

**Comment by duckyb** [comment]
@working-name any news on when the weblate site will be back up?

**Comment by working-name** [comment]
@duckyb my apologies, got slammed. Will get it back up and running during this holiday break (next 7 days) and then notify you.

**Comment by working-name** [comment]
@duckyb Hello there. Took a LONG time to get it done but could not go the upgrade route. Fresh new weblate install, so you'd have to create an account or log in using github/google.

Thank you for helping with the translation!
