### ISSUE TITLE
General collection of typos/errors/other.

### ISSUE THREAD

**Issue by Zarthus** [firasdib/regex101-translations#3]
I'm opening this issue to comment on any issues we've spotted with the first release, rather than opening separately. Feel free to append your own post.
- [x] `Like RegEx101? Support it by donating!` inconsistent casing with other spellings of `Regex`
- [x] `send me a personal email` implies informal use, I assume all requested inquiries are to be related to regex101, rather than "hey firasdib how are you doing".
- [x] `Please hold while your expression is being debugged...` => please wait
- [x]  `the condition is invalid (may be referencing a non-existent subpattern or group)` => "you may be"
- [x] `the verb is unknown/invalid` => This verb?

**Comment by haaami01** [comment]
> I’ve experienced it several times already, but I haven’t had such a jam problem lately.
