### ISSUE TITLE
Divide error messages, quickref, and "super technical" stuff into a separate file.

### ISSUE THREAD

**Issue by Zarthus** [firasdib/regex101-translations#5]
Some of the technical things can get very easily lost in translation and it will be difficult to look them up on Google when you don't have the English message. I suggest making it separate so people don't bother translating it unless they are confident they can explain it well in their language.

**Comment by firasdib** [comment]
If you have trouble translating them, leave as is. If you can translate them, translate them. Its fine to leave english as a backup. This will be continuous work which we will improve on with time. Some words make sense to leave in english, which is fine as well.
